config/routes.rb
Rails.application.routes.draw do
  # devise_for :admins
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
    sessions: 'admins/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "events#index"
  get '/events', to: 'events#index', defaults: { format: 'json' }
  # get '/events/back_index', to: 'events#back_index'
  resources:events 
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/admins/confirmations_controller.rb
# frozen_string_literal: true

class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/registrations_controller.rb
# frozen_string_literal: true

class Admins::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_in_path_for(resource)
   root_path
  end
  
  def after_sign_out_path_for(resource)
   root_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_admin!, except: [:show, :index]
  
  
  def index
    @events = Event.all
    respond_to do |format|
      format.html
      format.json { render 'calendar' }
    end
  end

  def show 
    @event = Event.find(params[:id])
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to root_path
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to root_path
  end
  
  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to root_path
  end
  
  private
  
  def event_params
    params.require(:event).permit(:title, :description,:start, :end) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/events/edit.html.erb
<h2>イベント編集</h2>

<%= form_with(model: @event, local: true) do |f| %>
  <div>
    <%= f.label :title, "タイトル" %>
  </div>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description, "詳細" %>
  </div>
  <div>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :start, "開始日" %>
  </div>
  <div>
    <%= f.date_field :start %>
  </div>
  <div>
    <%= f.label :end, "終了日" %>
  </div>
  <div>
    <%= f.date_field :end %>
  </div>
  <div>
    <%= f.submit "追加" %>
  </div>
<% end %>

app/views/events/index.html.erb
<script>
  let eventData = <%= raw @events.to_json  %>
</script>
<div id="calendar">
  
</div>

app/views/events/new.html.erb
<h2>新規イベント</h2>

<%= form_with(model: @event, local: true) do |f| %>
  <div>
    <%= f.label :title, "タイトル" %>
  </div>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description, "詳細" %>
  </div>
  <div>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :start, "開始日" %>
  </div>
  <div>
    <%= f.date_field :start %>
  </div>
  <div>
    <%= f.label :end, "終了日" %>
  </div>
  <div>
    <%= f.date_field :end %>
  </div>
  <div>
    <%= f.submit "編集" %>
  </div>
<% end %>

app/views/events/show.html.erb
<%= @event.title %>
<%= @event.description %>
<% if admin_signed_in? %>
  <%= link_to "編集",edit_event_path(@event.id) %>
  <%= link_to "削除",event_path(@event.id), method: :delete, data: { confirm: "本当に削除しますか？" } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IPU軽音予定</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="sp-menu">
      <h2>MENU</h2>
      <ul>
        <li>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
        </li>
        <li><%= link_to "予定追加", new_event_path %></li>
      </ul>
    </div>
    <header>
      <div class="container">
        <div class="header-contents">
          <div class="header-left">
            <h1 class="header-logo">
              <%= link_to root_path,  "data-turbolinks": false do %>
                <%= image_tag 'logo_transparent.png', class:"logo-img" %>
              <% end %>
            </h1>
          </div>
          <div class="header-right">
            <ul class="header-nav">
            <% unless admin_signed_in? %>
              <li>
                <%= link_to "ログイン", new_admin_session_path, class: 'btn btn-login' %>
              </li>
            <% else %>
              <div id="hm-icon">
                <a class="menu-trigger" href="#">
                  <span></span>
                  <span></span>
                  <span></span>
                </a>
              </div>
            <% end %>
            </ul>
          </div>
        </div>
      </div>
    </header>
    <main>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </main>
    <footer>
      
    </footer>
  </body>
</html>